packages:
  - packages/*
  - docs

catalog:
  '@luma.gl/core': ~9.1.9
  '@math.gl/core': ^4.1.0
  '@types/node': ^22.10.5
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@vitejs/plugin-react': ^4.3.4
  '@vivjs-experimental/viv': ^1.0.1
  anndata.js: ^0.0.2
  apache-arrow: ^17.0.0
  deck.gl: ~9.1.11
  parquet-wasm: ^0.6.1
  react: ^19.2.1
  react-dom: ^19.2.1
  typescript: ^5.7.3
  vite: ^7.2.7
  vite-plugin-dts: ^4.5.0
  vitest: ^3.1.4
  zarrita: ^0.5.4
  zod: ^4.1.13
