/** spatialdata `blobs()` fixture version served locally during vis demo dev. */
export const LOCAL_BLOBS_FIXTURE_VERSION = '0.7.2';

/**
 * URL for the local `blobs.zarr` fixture.
 *
 * During `pnpm --filter @spatialdata/vis dev`, Vite proxies `/test-fixtures`
 * to the fixture server (started alongside the demo on the host, default port 38473).
 */
export function getLocalBlobsFixtureUrl(origin?: string): string {
  const base =
    origin ?? (typeof window !== 'undefined' ? window.location.origin : 'http://127.0.0.1:5173');
  return `${base}/test-fixtures/v${LOCAL_BLOBS_FIXTURE_VERSION}/blobs.zarr`;
}

/** URL for the local JP2K codec fixture generated by `pnpm test:fixtures:generate:codecs`. */
export function getLocalJpeg2kCodecFixtureUrl(origin?: string): string {
  const base =
    origin ?? (typeof window !== 'undefined' ? window.location.origin : 'http://127.0.0.1:5173');
  return `${base}/test-fixtures/codecs/jpeg2k.zarr`;
}

/** URL for the JP2K fixture manifest emitted by the Python reference writer. */
export function getLocalJpeg2kCodecManifestUrl(origin?: string): string {
  const base =
    origin ?? (typeof window !== 'undefined' ? window.location.origin : 'http://127.0.0.1:5173');
  return `${base}/test-fixtures/codecs/jpeg2k.manifest.json`;
}
